### ISSUE TITLE
Test performance of application

### ISSUE THREAD

**Issue by AblionGE** [AblionGE/LocPrivLib#16]
Test the performance of the app in term of (with/without lib) :
- battery
- memory
- CPU

**Comment by AblionGE** [comment]
Some useful links :
- http://stackoverflow.com/questions/1957135/how-to-test-the-performance-of-an-android-application
- http://www.littleeye.co/features.php.html (seems to be good, but unusable right now)
- http://developer.android.com/tools/debugging/systrace.html
- http://developer.android.com/tools/debugging/debugging-studio.html

**Comment by AblionGE** [comment]
### Android Device Monitor

If you use the _Android Device Monitor_ you can observe the data transfered through network, the allocation of memory (we can for example observe that `AbstractWrapper.getWrapperList()` is the method in our app that uses a lot of memory, probably because it reads a file and checks if  sensors are present on the phone)
You also can have information about the heap state and some basic analysis on the current screen.

#### Systrace

Systrace (http://developer.android.com/tools/help/systrace.html#gui) gives you an interesting html page to go through an execution of the app.

It is also possible to have a trace only for a small portion of code.

**Comment by AblionGE** [comment]
We need to measure how much time it takes to make the obfuscation (if possible, separate in small parts (acquire data, process them, save them))

We also need to observe the cost of the obfuscation operations in term of computations (CPU usage, memory usage,...)

**Comment by AblionGE** [comment]
Everything about timing the obfuscation part was already done. Just need to collect the data to analyze them into a real situation.

**Comment by AblionGE** [comment]
I added 2 flags :
- LOGGING : if true, will log into console and into files the timings of `dataAvailable()` and `dataProduce()` in Virtual Sensors and all logs of LocPrivLib.
- PERFORMANCE : if true, will collect traces of `dataAvailable()` to observe CPU Time for each method called in it.

**Comment by AblionGE** [comment]
I did some measurements of `dataAvailable()` method (where the obfuscation computations are done).

Here are some results from experiments in real conditions (high values can be explained by another activity of the user at the same time) :

### Without obfuscation

Max : 9048 ms. (Clearly another activity of the user is involved)
Min : 1 ms.
Average  : 15 ms.
Number of measurements : 1420

---

Max : 93 ms.
Min : 1 ms.
Average  : 3 ms.
Number of measurements : 661

---

Max : 70 ms.
Min : 1 ms.
Average  : 3 ms.
Number of measurements : 353

### With Obfuscation

Max : 54596 ms.
Min : 235 ms.
Average  : 7641 ms.
Number of measurements : 1420

---

Max : 80529 ms.
Min : 661 ms.
Average  : 5687 ms.
Number of measurements : 661

---

Max : 5009 ms.
Min : 333 ms.
Average  : 1885 ms.
Number of measurements : 352

**Comment by berkeragir** [comment]
How many times did you perform the test for averaging?
Also, did you manage to evaluate the memory consumption?

For the average, it would be good to have all the timings and look at the 95% confidence interval (i.e., what are min and max values we get 95% of the time). I can do this if you provide them to me. This is more important than the actual max value we observe.

**Comment by AblionGE** [comment]
I did 3 sets of measurements and each contains a different number of measurements (I'll edit my post in a few minutes).

About the memory consumption, I still have to do it (tools that do it, like observing CPU, Memory, etc. take a non negligible amount of CPU/Memory so I have to do two sets of measurements (one with the lib, and one without) to compare them.
I'll do it tomorrow morning

About the average, I'll send you by mail the log files I have and I'll think about it tomorrow too :)

**Comment by AblionGE** [comment]
Here are 2 results from the Android Device Monitor for 2 measurements (not taken at the same time) with only one application running (tiny-GSN) but with other in background(Telegram, etc.)

Both of these measurements where made with a Brdige Virtual Sensor with the GPS wrapper.

### With Obfuscation

We can observe that the obfuscation is really important in term of CPU/Real time which is normal, but it seems to be a reasonable time.
![withobfuscation_bridgevirtualsensor_tinygsn model wrappers androidgpswrapper_1449093913042](https://cloud.githubusercontent.com/assets/4447612/11546568/6ce0ae8a-994e-11e5-8f97-5f43fa1a6f12.png)

### Without Obfuscation

![withoutobfuscation_bridgevirtualsensor_tinygsn model wrappers androidgpswrapper_1449093538696](https://cloud.githubusercontent.com/assets/4447612/11546574/72d3c160-994e-11e5-941d-6bd2007b0763.png)

**Comment by AblionGE** [comment]
Split into more precise issues ( #24 #25  and #26 )
