### ISSUE TITLE
Get semantic informations automatically

### ISSUE THREAD

**Issue by AblionGE** [AblionGE/LocPrivLib#22]
The goal is to load a map with informations about hospital, school, ... locations to be able to use semantic privacy protection mechanism.

Several problems to fix :
- How to get these data ?
- When should we load them to the phone ?
- Should we save all these information in the phone ?

**Comment by AblionGE** [comment]
To get the data, it is possible to get a part of the map from OpenStreetMap and then to export it and to find in the XML files the informations we want.

**Comment by AblionGE** [comment]
Some link on how we can achieve that easily : https://help.openstreetmap.org/questions/11004/download-a-map-and-extract-position-from-places-like-schools-hospitals-etc

**Comment by AblionGE** [comment]
@berkeragir I started to think about this functionality and I have two questions :
- I see in the current state of the application that there are more than 300 different number of semantic locations (for example : wall, hifi (?), driking_water, ...). Should we reduce this number ? I saw a file in the repo that list a few semantic locations (see below). With the API I want to use, I think we can easily have a "setting" file containing all the semantic locations we want (it's easy to add more locations later -> only a line in the file) and I'll be able to call the API only on these and not on all elements in a "box" on the map.

### Semantic locations from FourSquare

``` Airport
Bar
Beach
Cafeteria
Casino
Cemetery
Coffee Shop
College & University
Embassy / Consulate
Government Building
Hotel
Medical Center
Military Base
Movie Theater
Museum
Music Venue
Nightclub
Non-Profit
Park
Playground
Plaza
Post Office
Restaurant
School
Shop & Service
Spiritual Center
Sports Venue
Stadium
Voting Booth
Zoo
```

---

My second question is : how do you want to download data according to the position of the user with keeping anonymization of the position ?

**Comment by AblionGE** [comment]
This query should be enough to find useful informations :

```
( node
  (46.519,6.565,46.520,6.566);
  rel(bn)->.x;
  way(bn);
  rel(bw);
);
(
  ._;
  way(r);
);
(
  ._;
  node(r)->.x;
  node(w);
);
(
  ._;
  rel(br);
  rel(br);
);
out meta;
```

**Comment by AblionGE** [comment]
Better query :

```
<osm-script>
  <union into="_">
    <query into="_" type="relation">
      <has-kv k="amenity" modv="" v="university"/>
      <bbox-query e="6.6" into="_" n="46.6" s="46.5" w="6.5"/>
    </query>
    <query into="_" type="way">
      <has-kv k="amenity" modv="" v="university"/>
      <bbox-query e="6.6" into="_" n="46.6" s="46.5" w="6.5"/>
    </query>
    <query into="_" type="node">
      <has-kv k="amenity" modv="" v="university"/>
      <bbox-query e="6.6" into="_" n="46.6" s="46.5" w="6.5"/>
    </query>
  </union>
  <union into="_">
    <item set="_"/>
    <recurse from="_" into="_" type="down"/>
  </union>
  <print e="" from="_" geometry="skeleton" limit="" mode="body" n="" order="quadtile" s="" w=""/>
</osm-script>
```

**Comment by berkeragir** [comment]
What you suggest makes sense. Foursqare actually has around 700 semantic tags. I already have a python script to download them (they form a hierarchy). We can use the intersection between this list and the OpenStreetMap tags. I agree with your suggestion of using a settings file for this.

As for the privacy: When querying, if we make a query for an area large enough (say sth like 2x2 km2), then it shouldn't be a problem. Plus, once we query a region, we should keep a cache. This would reduce the risk.

**Comment by AblionGE** [comment]
Use only wifi to download semantic data

**Comment by AblionGE** [comment]
For storing semantic locations, when I have a "relation" in OSM, I only consider it if its type is "multipolygon" (http://wiki.openstreetmap.org/wiki/Types_of_relation). It will be saved as a Polygon in SpatiaLite.

For ways, I consider only ways that make an area (closed way). It will be saved as a Polygon in SpatiaLite.

**Comment by AblionGE** [comment]
Almost done. I'm in the testing phase. For now, the user has to decide when he wants to get semantic data around his position.

@berkeragir how do we decide we must update semantic data automatically ? Every x minutes ? each time you go out of an area that is already in the db (but that means do a lot of queries to the db to know when we must update...) ?

I will maybe do an activity to download semantic data on a box the user defines and do not do automatic update according to your current position.

**Comment by berkeragir** [comment]
@AblionGE, an update is needed really very infrequently, for instance, every 2-3 months. Venues do not change that fast.

**Comment by AblionGE** [comment]
Yes, But I meant, when you are in a zone where semantic data are not loaded, what should we do ? Nothing and the user must download himslef data for an area (that means I create a view to download semantic data) or do we find a way to do download dynamically according to the position of the user ?

I think I will to the view to do it manually and then it should not be so hard to do it automatically

**Comment by AblionGE** [comment]
For information, for a location relatively big (a bit more than Geneva canton's size), with logging it takes around 84157 milliseconds to load and save all semantic informations. As it is done once, this is not an issue.

**Comment by berkeragir** [comment]
I was thinking about an automatic system based on location (when wifi is available). Actually, if wifi is not available, maybe we can query a smaller area instead of a large area to avoid high data usage. 

I think 841 seconds could be problematic. The reason is that if this data download is done automatically, then it means that it will be triggered when location will be used. As a result, our library will be waiting for this data before it processes the location and gives an obfuscated location to the actual application. In this case, 841 seconds might be long (more than 10 minutes). Maybe we can try with smaller area sizes; what do you think?

**Comment by AblionGE** [comment]
It's 84 seconds, not 841 :) So it's not so big ! If we load small area it takes not so much time.

To load automatically data, what I can do is when I have a location from the wrapper, I can check if the location is in an already loaded area. If it is the case then fine. If it's not the case, I can skip this measurement (or keep it as such and compute sensitivity with closest semantic element from closest loaded area) and directly download a new area around the current position (size of this area depends if wifi is available or not)
