### ISSUE TITLE
Test more deeply the memory

### ISSUE THREAD

**Issue by AblionGE** [AblionGE/LocPrivLib#24]
Do some test in real situation (moving) with and without using the phone.

**Comment by AblionGE** [comment]
Useful video : https://www.youtube.com/watch?v=_CruQY55HOk

**Comment by AblionGE** [comment]
It is impossible with this tool to do measurements in real conditions. Thus, I will do some test at home and try to extract useful informations.

**Comment by berkeragir** [comment]
OK. Let me know of the results.

**Comment by AblionGE** [comment]
In term of memory, I saw that when we open Google Map window to set sensitivity levels manually, it takes a lot of memory (around half of the memory of the app, when it does nothing (no sensors, no wrappers)). But it's totally normal and we can't do anything (it's the google library).

Then, I tested how much memory it takes when it get data and process them (BridgeVirtualSensor, GPS location for sensitivity = 1).

In term of memory, the behavior is : each time a measurement is done, the allocated memory of the app is increased a bit (reducing the free memory the app can have).

![2015-12-22-135029_1722x419_scrot](https://cloud.githubusercontent.com/assets/4447612/11955581/61cfccc8-a8b3-11e5-8a2c-b57c8454b155.png)

And then, when there is no more free memory, instead of giving more memory to the application, the Garbage Collector is used to free useless memory and we can observe in next picture that the maximum allocation of memory for the app is reduced too (but it's not alwways the case) !

![2015-12-22-135305_1727x422_scrot](https://cloud.githubusercontent.com/assets/4447612/11955602/8bd9b934-a8b3-11e5-9345-f6280e1b6bb5.png)

![2015-12-22-135638_1714x416_scrot](https://cloud.githubusercontent.com/assets/4447612/11955641/da998414-a8b3-11e5-9058-342396099f11.png)

### Allocation Tracking

Using the allocation tracking tool in AndroidStudio, I did some measurements (tracking allocations when there were these small "steps") and the conclusions are that the objects created by TinyGSN and LocPrivLib take some place but not so much compared to java objects (by java object I mean, String, Integer, ...). Indeed, The allocation of TinyGSN in theses smalle "steps" is always around 0.18% of the memory used by the application, and it is around 25% for LocPrivLib. Thus, LocPrivLib objects are important for the allocated memory.

Nevertheless, when we go through these allocations using the "Group by Method" options, we have several methods that share the allocated memory during a small amount of time. If we go deeply in these method, we observe that in fact it is all of the time because of the `calculatePrivacyEstimation` method that takes memory. Thus, approximatively 95% percent of the allocations are made for this method. With these measurements, we also can observe that other methods need also memory allocation but in all cases, it is less than 1% of the allocated memory.

If we go more deeply in `calculatePrivacyEstimation()`, we observe that the part that needs more memory is to get the linkability graph. Nevertheless, I won't analyze to deeply the application.

I think it is enough to know that the allocated memory grows every time we receive data mainly because of the `calculatePrivacyEstimation` which seems totally normal as we are keeping the graph to estimate correctly the privacy.

Here is an example of what is the "call" tree for getting obfuscated values :

![allocation_method](https://cloud.githubusercontent.com/assets/4447612/11956316/98680f7e-a8b9-11e5-86ad-7307967b7f1a.png)

### Heap

For analyzing the heap[, I used the memory analyzer from Eclipse. It can gives us interesting informations about the state of the heap. The most interesting si the Histogram (the Dominator Tree is useful to find memory leaks but I won't use it here). It gives us the number of objects, the shallow heap and the retained heap (explanations here https://youtu.be/_CruQY55HOk?t=22m1s).

To do that, I made several heap dump files (20) and then I opened the "Histogram" window. Then I filtered the name of classes using the regex `(.*tiny.*|.*priv.*)`. Then, in all heap dump files, if I order using the "Shallow Heap" (the actual memory usage of this class in byte), the biggest class is always `org.epfl.locationprivacy.privacyEstimation.Event`. If I search the reference of this class (without using weak reference, see above for details in the video), I can see that's because of the `privacyEstimator`. This result is not surprising as mentionned in the allocation tracking section.

Then, I computed the number of objects from TinyGSN and LocPrivLib and the shallow heap (actually memory used in bytes) and I computed a percentage with the total number of objects and shallow heaps.

For one of the file, the result is :

```
===========FILE histogram_144411_tiny_priv.csv============
Number of Objects for TinyGSN and LocPrivLib : 117.0
Percentage of objects over total : 6.462624488375561E-4
Shallow Heap for TinyGsn and LocPrivLib : 4952.0
Percentage of Shallow Heap over total : 1.6666976311622376E-4
```

As you can see, it is really small. Nevertheless, we must notice that basic java objects are dominating this statistic and some of them are used during the process to compute the obfuscated area (bytes, strings, ...). As it is impossible to know where they come from in an easy manner, I didn't try to have this information because we already know from allocation tracking where we use memory during an execution.
