### ISSUE TITLE
Measurements of Energy in real condition

### ISSUE THREAD

**Issue by AblionGE** [AblionGE/LocPrivLib#25]
Do some measurements of energy in real condition (moving) with and without using the phone

**Comment by AblionGE** [comment]
These measurements where made on my personal phone (Samsung S4) having background application (Whats app, Telegram, mail...) but all of them where closed except TinyGSN and the phone was not used for one of the measurements set and in the other case I used it as usual (music, messaging, etc.)

The obfuscation mechanism was used and sensitivities set by hand (not all cells on the grid have the same sensitivity value).

## WithoutActivity

===========CONSIDERING ALL VALUES============
Max : 2138 mW
Min : 0 mW
Average  : 14 mW
stdeviation : 131.07249902248756 mW
Number of measurements : 3157
===========CONSIDERING 95% OF VALUES============
Max : 55 mW
Min : 0 mW
Average  : 1 mW
stdeviation : 13.96424004376894 mW
Number of measurements : 3000

## WithActivity

===========CONSIDERING ALL VALUES============
Max : 2138 mW
Min : 0 mW
Average  : 34 mW
stdeviation : 214.8720549536398 mW
Number of measurements : 3692
===========CONSIDERING 95% OF VALUES============
Max : 428 mW
Min : 0 mW
Average  : 3 mW
stdeviation : 38.09199390948182 mW
Number of measurements : 3509

**Comment by berkeragir** [comment]
Good. We should discuss on this a little bit. Did the phone's battery last the day after all this?

**Comment by AblionGE** [comment]
Don't know, it's really changing on my phone, but not especially if I remember well.

But compared to other app, it seems not be unreasonable
