### ISSUE TITLE
Do Privacy Estimation

### ISSUE THREAD

**Issue by AblionGE** [AblionGE/LocPrivLib#27]
- [x] Get data from CHUV
- [x] Create a wrapper that read a file
- [x] Create a virtual sensor to get data from the new wrapper and obfuscate these data
  - [x] Print in a file the exact location
  - [x] Print in a file the obfuscated location
  - [x] Print in a file the privacy estimation value
  - [x] Print in a file the Theta*sensitivity value

**Comment by AblionGE** [comment]
@berkeragir I need to have the data from CHUV please !

**Comment by AblionGE** [comment]
@berkeragir other question : when I will obfuscate data from CHUV, what semantic sensitivities should I set ? All to 0 ? All to 1 ?

**Comment by berkeragir** [comment]
I sent you the CHUV data. As for the sensitivities: It is not useful if we set all of them to 0 or 1. For now, please select some (like 20) tags and set some sensitivities based on your own common sense. For example, hospital should be 1, a bar could be 0.4, restaurant 0.3, university 0.5, bank 0.8, park 0, fast food 0.2, cafe 0.2, commercial 0.5, residential 0,7, etc. I will try to give more soon.

**Comment by AblionGE** [comment]
Creation of wrapper is done here : https://github.com/AblionGE/gsn/issues/26

**Comment by AblionGE** [comment]
@berkeragir for the `privacyEstimation` value, do you want all values for obfuscating one location or only the final one (same for obfuscated region) ?

**Comment by AblionGE** [comment]
These are the semantic sensitivities I use for testing CHUV data :

```
SemanticLocationsDataSource.getInstance(ActivityHome.this).updateSemanticLocation("university", 50);
SemanticLocationsDataSource.getInstance(ActivityHome.this).updateSemanticLocation("bar", 40);
SemanticLocationsDataSource.getInstance(ActivityHome.this).updateSemanticLocation("hospital", 100);
SemanticLocationsDataSource.getInstance(ActivityHome.this).updateSemanticLocation("bank", 80);
SemanticLocationsDataSource.getInstance(ActivityHome.this).updateSemanticLocation("restaurant", 30);
SemanticLocationsDataSource.getInstance(ActivityHome.this).updateSemanticLocation("park", 0);
SemanticLocationsDataSource.getInstance(ActivityHome.this).updateSemanticLocation("fast_food", 40);
SemanticLocationsDataSource.getInstance(ActivityHome.this).updateSemanticLocation("hotel", 50);
SemanticLocationsDataSource.getInstance(ActivityHome.this).updateSemanticLocation("clinic", 100);
SemanticLocationsDataSource.getInstance(ActivityHome.this).updateSemanticLocation("nightclub", 80);
SemanticLocationsDataSource.getInstance(ActivityHome.this).updateSemanticLocation("post_office", 10);
SemanticLocationsDataSource.getInstance(ActivityHome.this).updateSemanticLocation("prison", 100);
SemanticLocationsDataSource.getInstance(ActivityHome.this).updateSemanticLocation("museum", 5);
SemanticLocationsDataSource.getInstance(ActivityHome.this).updateSemanticLocation("stadium", 25);
SemanticLocationsDataSource.getInstance(ActivityHome.this).updateSemanticLocation("train_station", 15);
SemanticLocationsDataSource.getInstance(ActivityHome.this).updateSemanticLocation("zoo", 30);
SemanticLocationsDataSource.getInstance(ActivityHome.this).updateSemanticLocation("police", 70);
SemanticLocationsDataSource.getInstance(ActivityHome.this).updateSemanticLocation("ferry_terminal", 15);
SemanticLocationsDataSource.getInstance(ActivityHome.this).updateSemanticLocation("embassy", 90);
SemanticLocationsDataSource.getInstance(ActivityHome.this).updateSemanticLocation("aerodrome", 70);
SemanticLocationsDataSource.getInstance(ActivityHome.this).updateSemanticLocation("cemetery", 30);
SemanticLocationsDataSource.getInstance(ActivityHome.this).updateSemanticLocation("commercial", 75);
```

**Comment by AblionGE** [comment]
I had to comeback with the logging method in `AdaptiveProtection` (coherence problem...). Now, it will create one folder per events in the same millisecond (as initially). Thus, for analyzing data we will need to put all informations we want in one file using bash (for ex.)

**Comment by AblionGE** [comment]
@berkeragir what do you want I compute with these values ? Max, min and average (for privacyEstimation) ?
