### ISSUE TITLE
Generate automatically cells around the current position

### ISSUE THREAD

**Issue by AblionGE** [AblionGE/LocPrivLib#5]
Create automatically cells around the current position with a grid of 20x20.
The `locId` created must be stored in the database.
- [x] Compute cell coordinates from any coordinates
- [x] Compute cell id from GPS
- [x] Save only cells with a sensitivity value

**Comment by AblionGE** [comment]
Link about coordinates : http://gis.stackexchange.com/questions/8650/how-to-measure-the-accuracy-of-latitude-and-longitude

**Comment by AblionGE** [comment]
Circle of latitude : https://fr.wikipedia.org/wiki/Parall%C3%A8le_%28g%C3%A9ographie%29

**Comment by AblionGE** [comment]
For computing cell ID : https://en.wikipedia.org/wiki/Pairing_function

**Comment by AblionGE** [comment]
For the moment, things are coded but not tested

**Comment by berkeragir** [comment]
The pairing function you referenced seems to only work on natural numbers (i.e., for x >= 0). Am I wrong? We need to cover the negative latitude and longitude values too. Did we already find a solution to that?

For the cells to draw around the current position: do you think we can draw these just to fill the currently visible map on the screen? If the user zooms out, we can draw maybe a little bit more, but we can stop drawing at certain zoom level (for example, if the user zooms out to view a whole canton, or country). Then, when user zooms in again to a certain level, we can refresh the drawing for the currently visible part of the map. This allows the user to set sensitivity level for a far-away place (for instance, you want to set sensitivity for a place in Geneva when you're in Lausanne).

**Comment by AblionGE** [comment]
For the pairing function, I simply add 90 and 180, I make the computations and then and remove 90 and 180.

For the cells to draw, that's a good idea. I add an issue and when my bugs will be resolved I'll do that ! Related to #8

**Comment by AblionGE** [comment]
Actually, I can draw cells with a certain width depending on the latitude. Problem : in Switzerland, cells are too large... I will investigate what is my mistake

**Comment by AblionGE** [comment]
To compute the grid and to draw it, I compute the top left corner of the grid and then, for each row, I simply compute `gridTopLeftCorner-(i*100 meters)` and I call `findCellTopLeftPoint(LatLng position)` on the new `LatLng` object. It gives us a grid that is not a square because at each latitude, the longitude for 100 meters is not always the same.

I also can note that the _Haversine function_ is really usefull !
